apiVersion: apps/v1
kind: Deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          ports:
            - containerPort: 8080
#volumeMounts:
#      - name: jenkins-home
#        mountPath: /data/jenkins-volume/
#  volumes:
#      - name: jenkins-home
#        emptyDir: {}